Repository janhq/docs, pull requests merged in 2024-06, with the labels that each got.

#255 docs: Quickstart revamp
  src/pages/cortex/quickstart.mdx
Labels: type: documentation

#256 docs: Update the client libraries and the cortex architecture pages
  src/pages/cortex/_assets/architecture.png
  src/pages/cortex/architecture.mdx
  src/pages/cortex/py-library.mdx
  src/pages/cortex/ts-library.mdx
Labels: type: documentation

#257 docs: nits
  src/pages/cortex/architecture.mdx
Labels: type: documentation

#261 docs: Update the redirects
  _redirects
Labels: type: documentation

#258 feat: OAI coverage UI
  package.json
  src/components/OAICoverage/index.tsx
  src/pages/cortex/server.mdx
  yarn.lock
Labels: type: feature request

#265 docs: Update the redirects and link Cortex button to the new web
  _redirects
  theme.config.tsx
Labels: type: documentation

#267 feat: added Homebrew logo on footer
  public/assets/images/general/logo-homebrew.svg
  src/components/FooterMenu/index.tsx
Labels: type: feature request

#269 fix: conditional download button for apple m series or intel
  src/components/DropdownDownload/index.tsx
  src/components/Home/Hero/index.tsx
Labels: type: bug
