Repository janhq/docs, pull requests merged in 2024-03, with the labels that each got.

#3 chore: migrate new docs
  docusaurus.config.js
  yarn.lock
Labels: type: chore

#4 fix: add missing content in migration
  docs/about/assets/solar-punk.webp
  docs/about/assets/vision-1.webp
  docs/about/vision.md
  docs/pending-content/blogpost/02-surpassing-chatgpt-with-open-source-alternatives.mdx
  docs/pending-content/blogpost/assets/mistral-comparasion.png
  docs/pending-content/blogpost/assets/nitro-on-jan.png
  docs/pending-content/blogpost/assets/rag-comparasion.png
  docs/pending-content/blogpost/assets/stealth-comparasion.png
  docs/pending-content/blogpost/finetune-with-docs.mdx
  docs/pending-content/blogpost/img/about-nitro.png
  docs/pending-content/blogpost/img/finetuned-respond-2.png
  docs/pending-content/blogpost/img/finetuned-response.png
  sidebars.js
  src/containers/DownloadApp/index.js
  src/containers/Testimonial/index.js
  src/pages/download.js
  src/pages/index.js
  src/styles/components/base.scss
  src/styles/components/font.scss
  src/styles/main.scss
  static/font/PPEditorialNew-Regular.otf
  static/font/PPEditorialNew-RegularItalic.otf
  static/font/PPEditorialNew-Ultrabold.otf
  static/font/PPEditorialNew-UltraboldItalic.otf
  static/font/PPEditorialNew-Ultralight.otf
  static/font/PPEditorialNew-UltralightItalic.otf
Labels: type: bug

#6 docs: hide the unfinished content & repoint edit button url
  bar.js
  docs/developer/02-build-assistant/01-your-first-assistant.md
  docs/developer/02-build-assistant/02-assistant-anatomy.md
  docs/developer/02-build-assistant/03-package-your-assistant.md
  docs/developer/02-build-assistant/README.mdx
  docs/developer/03-build-engine/01-your-first-engine.md
  docs/developer/03-build-engine/02-engine-anatomy.md
  docs/developer/03-build-engine/03-package-your-engine.md
  docs/developer/03-build-engine/README.mdx
  docs/developer/03-build-engine/asset/plugin.png
  docs/developer/04-build-extension/01-your-first-extension.md
  docs/developer/04-build-extension/02-extension-anatomy.md
  docs/developer/04-build-extension/03-package-your-extension.md
  docs/developer/04-build-extension/README.mdx
  docs/guides/get-started/overview.mdx
  docs/guides/installation/README.mdx
  docusaurus.config.js
  sidebars.js
  src/components/HomepagePrimaryFeatures/index.js
  src/pages/docs.js
Labels: type: documentation

#7 fix: no index youtube iframe
  README.md
  docusaurus.config.js
  src/containers/Testimonial/index.js
  static/robots.txt
Labels: type: bug

#35 docs: Hide empty contents, fix hub page and updated quickstart content
  docs/developer/05-framework/03-engineering/fine-tuning.md
  docs/developer/05-framework/03-engineering/prompts.md
  docs/guides/get-started/quickstart.mdx
  docusaurus.config.js
  src/pages/docs.js
Labels: type: documentation

#36 fix: change josefin into PPEditorialNew font
  tailwind.config.js
Labels: type: bug

#46 Update CICD for nextra
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/discussion-thread.md
  .github/ISSUE_TEMPLATE/documentation-request.md
  .github/ISSUE_TEMPLATE/epic-request.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/pull_request_template.md
  .github/workflows/auto-assign-author.yml
  .github/workflows/auto-label-conventional-commits.yaml
  .github/workflows/clean-cloudflare-page-preview-url-and-r2.yml
  .github/workflows/jan-docs.yml
  next.config.mjs
Labels: type: feature request

#48 docs: Update acknowledgements.md
  docs/acknowledgements.md
Labels: type: documentation

#51 docs: acks
  docs/about/about.md
  docs/about/faq.md
  docs/acknowledgements.md
  docs/privacy/privacy.md
Labels: type: documentation
