Repository janhq/docs, pull requests merged in 2024-05, with the labels that each got.

#175 fix: fetch redirect og:image
  theme.config.tsx
Labels: type: bug

#179 docs: Update integrations pages and remove the older docs folder
  _redirects
  docs/guides/user-guides/jan-data-folder.mdx
  docs/guides/user-guides/manage-models.mdx
  docs/guides/user-guides/manage-threads.mdx
  docs/guides/user-guides/use-tools.mdx
  src/pages/integrations/coding/continue-dev.mdx
  src/pages/integrations/index.mdx
  src/pages/integrations/messaging/llmcord.mdx
Labels: type: documentation

#180 docs: nits and grammar
  src/pages/about/index.mdx
  src/pages/about/vision.mdx
  src/pages/changelog/2023-12-21-faster-inference-across-platform.mdx
  src/pages/changelog/2024-01-16-settings-options-right-panel.mdx
  src/pages/changelog/2024-01-29-local-api-server.mdx
  src/pages/changelog/2024-02-05-jan-data-folder.mdx
  src/pages/changelog/2024-02-26-home-servers-with-helm.mdx
  src/pages/changelog/2024-03-11-import-models.mdx
  src/pages/changelog/2024-03-19-nitro-tensorrt-llm-extension.mdx
  src/pages/changelog/2024-04-02-groq-api-integration.mdx
  src/pages/changelog/2024-04-15-new-mistral-extension.mdx
  src/pages/changelog/2024-25-04-llama3-command-r-hugginface.mdx
  src/pages/docs/assistants.mdx
  src/pages/docs/built-in/llama-cpp.mdx
  src/pages/docs/built-in/tensorrt-llm.mdx
  src/pages/docs/desktop-installation/linux.mdx
  src/pages/docs/error-codes.mdx
  src/pages/docs/extensions.mdx
  src/pages/docs/index.mdx
  src/pages/docs/installing-extension.mdx
  src/pages/docs/local-inference/ollama.mdx
  src/pages/docs/models/manage-models.mdx
  src/pages/docs/models/model-parameters.mdx
  src/pages/docs/quickstart.mdx
  src/pages/docs/remote-inference/generic-openai.mdx
  src/pages/docs/remote-inference/groq.mdx
  src/pages/docs/remote-inference/mistralai.mdx
  src/pages/docs/remote-inference/openai.mdx
  src/pages/docs/server-installation/aws.mdx
  src/pages/docs/server-installation/azure.mdx
  src/pages/docs/server-installation/gcp.mdx
  src/pages/docs/server-installation/onprem.mdx
  src/pages/docs/settings.mdx
  src/pages/docs/shortcuts.mdx
  src/pages/docs/tools/retrieval.mdx
  src/pages/docs/troubleshooting.mdx
  src/pages/privacy.mdx
Labels: type: documentation, type: enhancement

#181 Update the docs
  src/pages/docs/_assets/set-model.gif
  src/pages/docs/_assets/set-url.gif
  src/pages/docs/_assets/ui.gif
  src/pages/docs/local-api.mdx
  src/pages/docs/remote-inference/generic-openai.mdx
  src/pages/docs/remote-inference/groq.mdx
  src/pages/docs/remote-inference/mistralai.mdx
  src/pages/docs/remote-inference/openai.mdx
  src/pages/docs/server-installation/aws.mdx
  src/pages/docs/server-installation/azure.mdx
  src/pages/docs/server-installation/gcp.mdx
  src/pages/docs/server-installation/onprem.mdx
  src/pages/docs/settings.mdx
Labels: type: documentation

#182 docs: Update to reflect the new app behavior
  _redirects
  src/pages/docs/built-in/llama-cpp.mdx
  src/pages/docs/models/manage-models.mdx
  src/pages/docs/server-installation/onprem.mdx
Labels: type: documentation

#201 fix: update copyright footer
  src/components/FooterMenu/index.tsx
Labels: type: bug

#202 Update the quickstart, jan data folder, and desktop installations
  _redirects
  src/pages/docs/_assets/amd.gif
  src/pages/docs/_assets/delete-data.png
  src/pages/docs/_assets/instructions.gif
  src/pages/docs/_assets/models.gif
  src/pages/docs/_meta.json
  src/pages/docs/data-folder.mdx
  src/pages/docs/desktop-installation/_meta.json
  src/pages/docs/desktop-installation/linux.mdx
  src/pages/docs/desktop-installation/mac.mdx
  src/pages/docs/desktop-installation/windows.mdx
  src/pages/docs/desktop.mdx
  src/pages/docs/desktop/_meta.json
  src/pages/docs/desktop/linux.mdx
  src/pages/docs/desktop/mac.mdx
  src/pages/docs/desktop/windows.mdx
  src/pages/docs/local-models/_meta.json
  src/pages/docs/local-models/lmstudio.mdx
  src/pages/docs/local-models/ollama.mdx
  src/pages/docs/models/manage-models.mdx
  src/pages/docs/quickstart.mdx
  src/pages/docs/remote-inference/_meta.json
  src/pages/docs/remote-models/_meta.json
  src/pages/docs/remote-models/generic-openai.mdx
  src/pages/docs/remote-models/groq.mdx
  src/pages/docs/remote-models/mistralai.mdx
  src/pages/docs/remote-models/openai.mdx
  src/pages/docs/remote-models/openrouter.mdx
  src/pages/docs/server-installation/aws.mdx
  src/pages/docs/server-installation/azure.mdx
  src/pages/docs/server-installation/gcp.mdx
  src/pages/docs/server-installation/onprem.mdx
Labels: type: documentation

#213 docs: added the cortex callout and update the hardware into tabs
  src/pages/cortex/index.mdx
  src/pages/docs/desktop/linux.mdx
  src/pages/docs/desktop/mac.mdx
  src/pages/docs/desktop/windows.mdx
Labels: type: documentation

#214 feat: create image caption component
  src/components/Download/index.tsx
  src/components/Home/Hero/index.tsx
  src/components/Home/Statistic/index.tsx
  src/components/ImageCaption/index.tsx
  src/pages/docs/index.mdx
Labels: good first issue, type: feature request

#211 docs: cortex initial docs
  src/pages/cortex/_meta.json
  src/pages/cortex/architecture.mdx
  src/pages/cortex/cli.mdx
  src/pages/cortex/cortex-cpp.mdx
  src/pages/cortex/cortex-llamacpp.mdx
  src/pages/cortex/cortex-openvino.mdx
  src/pages/cortex/cortex-python.mdx
  src/pages/cortex/cortex-tensorrt-llm.mdx
  src/pages/cortex/desktop-installation.mdx
  src/pages/cortex/desktop-installation/_meta.json
  src/pages/cortex/desktop-installation/linux.mdx
  src/pages/cortex/desktop-installation/mac.mdx
  src/pages/cortex/desktop-installation/windows.mdx
  src/pages/cortex/index.mdx
  src/pages/cortex/quickstart.mdx
  src/pages/cortex/text-generation.mdx
Labels: type: documentation

#220 docs: Update quickstart.mdx
  src/pages/cortex/quickstart.mdx
Labels: type: documentation

#222 docs: Update the API Reference file
  public/openapi/jan.json
Labels: type: documentation

#223 docs: Update the API swagger file
  public/openapi/jan.json
Labels: type: documentation

#228 docs: scaffold basic usage
  package.json
  src/pages/cortex/_meta.json
  src/pages/cortex/cli-overview.mdx
  src/pages/cortex/cli.mdx
  src/pages/cortex/clients.mdx
  src/pages/cortex/cortex-chat.mdx
  src/pages/cortex/cortex-models.mdx
  src/pages/cortex/cortex-pull.mdx
  src/pages/cortex/cortex-run.mdx
  src/pages/cortex/py-library.mdx
  src/pages/cortex/server.mdx
  src/pages/cortex/ts-library.mdx
Labels: type: documentation

#231 docs: Update per feedbacks
  src/pages/cortex/_meta.json
  src/pages/cortex/cli-overview.mdx
  src/pages/cortex/cli.mdx
  src/pages/cortex/cli/_meta.json
  src/pages/cortex/cli/chat.mdx
  src/pages/cortex/cli/models.mdx
  src/pages/cortex/cli/pull.mdx
  src/pages/cortex/cli/run.mdx
  src/pages/cortex/command-line.mdx
  src/pages/cortex/cortex-chat.mdx
  src/pages/docs/built-in/tensorrt-llm.mdx
Labels: type: documentation

#235 feat: update total download from api github
  src/components/Home/BuiltWithLove/index.tsx
  src/components/Home/CTADownload/index.tsx
  src/components/Home/Hero/index.tsx
  src/components/Home/Statistic/index.tsx
  src/pages/about/_meta.json
  src/pages/cortex/_meta.json
  src/pages/index.mdx
  src/utils/format.ts
Labels: type: feature request

#238 fix: setup analytics
  src/pages/_app.mdx
Labels: type: bug

#237 docs: Update the Remote APIs section
  src/pages/cortex/cli.mdx
  src/pages/docs/_assets/model-anthropic.gif
  src/pages/docs/_assets/model-cohere.gif
  src/pages/docs/_assets/model-martian.gif
  src/pages/docs/_assets/server-anthropic.gif
  src/pages/docs/_assets/server-cohere.gif
  src/pages/docs/_assets/server-martian.gif
  src/pages/docs/_assets/start-anthropic.gif
  src/pages/docs/_assets/start-cohere.gif
  src/pages/docs/_assets/start-martian.gif
  src/pages/docs/remote-models/_meta.json
  src/pages/docs/remote-models/anthropic.mdx
  src/pages/docs/remote-models/cohere.mdx
  src/pages/docs/remote-models/martian.mdx
Labels: type: documentation

#243 docs: Update the CLI pages
  src/pages/cortex/cli/models.mdx
  src/pages/cortex/cli/models/_meta.json
  src/pages/cortex/cli/models/update.mdx
  src/pages/cortex/cli/pull.mdx
Labels: type: documentation

#247 docs: fix the URL
  _redirects
Labels: type: documentation

#252 docs: Update cortex download desc
  src/pages/cortex/cli.mdx
Labels: type: documentation
