Repository janhq/docs, pull requests merged in 2024-04, with the labels that each got.

#66 docs: Updated the openapi json
  openapi/jan.json
Labels: P1: important, type: documentation

#71 fix: update missing path scalar json
  src/components/APIReference/index.tsx
  src/pages/about/_meta.json
  src/pages/about/teams/_meta.json
Labels: type: bug

#72 fix: remove env
  .env
Labels: type: bug

#73 fix: content about us
  src/pages/_meta.json
  src/pages/about/_assets/solar-punk.webp
  src/pages/about/_assets/vision-1.webp
  src/pages/about/_meta.json
  src/pages/about/how-we-work/_meta.json
  src/pages/about/vision.mdx
Labels: type: bug

#74 fix: type of page
  src/pages/_meta.json
Labels: type: bug

#75 fix: missing gtmid format
  src/pages/_app.mdx
Labels: type: bug

#77 docs: Updated the redirects and hide the developer section
  _redirects
  src/pages/_meta.json
  src/pages/developer/_assets/clean-architecture.jpg
  src/pages/developer/_assets/extension-callouts.png
  src/pages/developer/_assets/jan-views.png
  src/pages/developer/_meta.json
  src/pages/developer/architecture.mdx
  src/pages/developer/file-based.mdx
  src/pages/developer/framework.mdx
  src/pages/developer/framework/engineering.mdx
  src/pages/developer/framework/engineering/_meta.json
  src/pages/developer/framework/engineering/assistants.mdx
  src/pages/developer/framework/engineering/chats.mdx
  src/pages/developer/framework/engineering/engine.mdx
  src/pages/developer/framework/engineering/files.mdx
  src/pages/developer/framework/engineering/fine-tuning.mdx
  src/pages/developer/framework/engineering/messages.mdx
  src/pages/developer/framework/engineering/models.mdx
  src/pages/developer/framework/engineering/prompts.mdx
  src/pages/developer/framework/engineering/threads.mdx
  src/pages/developer/framework/product.mdx
  src/pages/developer/framework/product/_assets/chat-screen.png
  src/pages/developer/framework/product/_assets/hub-screen.png
  src/pages/developer/framework/product/_assets/settings-screen.png
  src/pages/developer/framework/product/_assets/system-screen.png
  src/pages/developer/framework/product/_meta.json
  src/pages/developer/framework/product/chat.mdx
  src/pages/developer/framework/product/hub.mdx
  src/pages/developer/framework/product/jan.mdx
  src/pages/developer/framework/product/settings.mdx
  src/pages/developer/framework/product/system-monitor.mdx
  src/pages/developer/index.mdx
  src/pages/developer/install-and-prerequisites.mdx
  src/pages/developer/user-interface.mdx
Labels: type: documentation

#81 docs: Update redirect
  _redirects
Labels: type: documentation

#82 fix: resolve github broken link
  src/components/Blog/index.tsx
  src/components/Changelog/index.tsx
  src/components/Download/CardDownload.tsx
  src/components/FooterMenu/index.tsx
  src/components/Home/BuiltWithLove/index.tsx
  src/components/Home/CTANewsletter/index.tsx
  src/components/Home/Feature/index.tsx
  src/components/Home/Principles/index.tsx
  src/pages/_meta.json
  src/styles/general.scss
  theme.config.tsx
Labels: type: bug

#86 docs: Removed outadated section (framework)
  src/pages/docs/_meta.json
  src/pages/docs/engineering-specs/_assets/chat-screen.png
  src/pages/docs/engineering-specs/_assets/hub-screen.png
  src/pages/docs/engineering-specs/_assets/settings-screen.png
  src/pages/docs/engineering-specs/_assets/system-screen.png
  src/pages/docs/engineering-specs/_meta.json
  src/pages/docs/engineering-specs/hub.mdx
  src/pages/docs/engineering-specs/settings.mdx
  src/pages/docs/engineering-specs/system-monitor.mdx
Labels: type: documentation

#90 docs: Fix redirect broken linsks
  _redirects
Labels: type: documentation

#92 fix: wrong _meta.json about folder
  src/pages/about/_meta.json
Labels: type: bug

#93 fix: update og image
  public/assets/images/general/og-image.png
Labels: type: bug

#94 docs: Updated redirects and overview page
  _redirects
  src/pages/docs/index.mdx
Labels: type: documentation

#95 fix: scalar system theme
  src/components/APIReference/index.tsx
  src/components/Blog/index.tsx
Labels: type: bug

#96 Hide the Product section
  src/components/FooterMenu/index.tsx
  src/pages/_meta.json
  src/pages/product/_assets/image-1.png
  src/pages/product/_assets/image-2.png
  src/pages/product/_assets/image-3.png
  src/pages/product/_assets/image-4.png
  src/pages/product/_assets/image.png
  src/pages/product/_meta.json
  src/pages/product/features.mdx
  src/pages/product/features/agents-framework.mdx
  src/pages/product/features/api-server.mdx
  src/pages/product/features/data-security.mdx
  src/pages/product/features/extensions-framework.mdx
  src/pages/product/features/local.mdx
  src/pages/product/features/remote.mdx
  src/pages/product/home-server.mdx
  src/pages/product/index.mdx
Labels: type: documentation

#97 docs: Updated the Scalar dependencies to fix the response schema ui
  package.json
  yarn.lock
Labels: P1: important, type: documentation

#98 docs: Update llamacpp.mdx
  src/pages/docs/local-inference/llamacpp.mdx
Labels: type: documentation

#100 fix: missing link url default system download button
  src/components/DropdownDownload/index.tsx
Labels: type: bug

#110 docs: Update website stat
  src/components/Home/CTADownload/index.tsx
  src/components/Home/Hero/index.tsx
  src/components/Home/Statistic/index.tsx
Labels: type: documentation

#111 docs: Updated the docs for the 4.11 release
  src/pages/docs/extensions.mdx
  src/pages/docs/local-api.mdx
  src/pages/docs/remote-inference/generic-openai.mdx
  src/pages/docs/remote-inference/groq.mdx
  src/pages/docs/remote-inference/mistralai.mdx
  src/pages/docs/remote-inference/openai.mdx
  src/pages/docs/remote-inference/router.mdx
  src/pages/docs/threads.mdx
  src/pages/docs/troubleshooting.mdx
Labels: type: documentation

#104 feat: Doc updates
  src/pages/docs/_meta.json
  src/pages/docs/hardware/_meta.json
  src/pages/docs/hardware/laptop.md
  src/pages/docs/hardware/overview.md
  src/pages/docs/hardware/pc.md
  src/pages/docs/hardware/workstation.md
  src/pages/docs/installation/_assets/helm_resources.png
  src/pages/docs/installation/server.mdx
  src/pages/docs/local-inference/llamacpp.mdx
  src/pages/docs/setup-gpu/amd.mdx
  src/pages/docs/setup-gpu/intel.mdx
  src/pages/docs/setup-gpu/metal.mdx
  src/pages/docs/setup-gpu/nvidia.mdx
  src/pages/post/ceo-guide-to-llm.mdx
Labels: P1: important, type: documentation, type: feature request

#112 docs: added the section for the app logging settings
  src/pages/docs/extensions.mdx
Labels: type: documentation

#113 docs: Revamped the content and hide the empty pages
  _redirects
  src/pages/docs/hardware/_meta.json
  src/pages/docs/hardware/laptop.md
  src/pages/docs/hardware/overview.md
  src/pages/docs/hardware/pc.md
  src/pages/docs/hardware/workstation.md
  src/pages/docs/installation/server.mdx
  src/pages/docs/setup-gpu/amd.mdx
  src/pages/docs/setup-gpu/intel.mdx
  src/pages/docs/setup-gpu/metal.mdx
  src/pages/docs/setup-gpu/nvidia.mdx
Labels: type: documentation

#117 docs: Updated the docs
  src/pages/docs/_assets/configure.gif
  src/pages/docs/_meta.json
  src/pages/docs/hardware-setup/_meta.json
  src/pages/docs/hardware-setup/amd.mdx
  src/pages/docs/hardware-setup/intel.mdx
  src/pages/docs/hardware-setup/mac.mdx
  src/pages/docs/hardware-setup/nvidia.mdx
  src/pages/docs/models.mdx
  src/pages/docs/quickstart.mdx
  src/pages/docs/use-tools.mdx
Labels: type: documentation

#118 docs: updated the Using Models page.
  src/pages/docs/models.mdx
Labels: type: documentation

#119 fix: update typo
  src/components/Home/APIStructure/index.tsx
Labels: type: bug

#121 docs: Update redirects to fix broken link
  _redirects
Labels: type: documentation

#122 fix: client side error on blog page
  src/pages/blog.mdx
Labels: type: bug

#123 docs: Updated the docs
  src/pages/docs/advanced.mdx
  src/pages/docs/architecture.mdx
  src/pages/docs/assistants.mdx
  src/pages/docs/extensions.mdx
  src/pages/docs/hardware-setup/amd.mdx
  src/pages/docs/hardware-setup/intel.mdx
  src/pages/docs/hardware-setup/nvidia.mdx
  src/pages/docs/index.mdx
  src/pages/docs/installation/desktop.mdx
  src/pages/docs/installation/server.mdx
  src/pages/docs/integrations/discord.mdx
  src/pages/docs/integrations/interpreter.mdx
  src/pages/docs/integrations/raycast.mdx
  src/pages/docs/integrations/vscode.mdx
  src/pages/docs/local-api.mdx
  src/pages/docs/local-inference/llamacpp.mdx
  src/pages/docs/local-inference/lmstudio.mdx
  src/pages/docs/local-inference/ollama.mdx
  src/pages/docs/local-inference/tensorrtllm.mdx
  src/pages/docs/models.mdx
  src/pages/docs/quickstart.mdx
  src/pages/docs/remote-inference/generic-openai.mdx
  src/pages/docs/remote-inference/groq.mdx
  src/pages/docs/remote-inference/mistralai.mdx
  src/pages/docs/remote-inference/openai.mdx
  src/pages/docs/remote-inference/router.mdx
  src/pages/docs/threads.mdx
  src/pages/docs/troubleshooting.mdx
  src/pages/docs/use-tools.mdx
Labels: type: documentation

#129 docs: Updated the docs
  src/pages/docs/_meta.json
  src/pages/docs/extensions.mdx
  src/pages/docs/hardware-setup.mdx
  src/pages/docs/installation/desktop.mdx
  src/pages/docs/installation/server.mdx
  src/pages/docs/integrations/discord.mdx
  src/pages/docs/integrations/interpreter.mdx
  src/pages/docs/integrations/vscode.mdx
  src/pages/docs/local-inference/llamacpp.mdx
  src/pages/docs/models.mdx
  src/pages/docs/remote-inference/groq.mdx
  src/pages/docs/remote-inference/mistralai.mdx
  src/pages/docs/remote-inference/openai.mdx
  src/pages/docs/troubleshooting.mdx
Labels: type: documentation

#128 feat: update copies footer
  src/components/FooterMenu/index.tsx
Labels: type: enhancement, type: feature request

#133 fix resize image
  next.config.mjs
  package.json
  public/assets/images/homepage/app-frame-dark.webp
  public/assets/images/homepage/app-frame-light.webp
  public/assets/images/homepage/features01.webp
  public/assets/images/homepage/features01dark.webp
  public/assets/images/homepage/features02.webp
  public/assets/images/homepage/features02dark.webp
  public/assets/images/homepage/features03.webp
  public/assets/images/homepage/features03dark.webp
  public/assets/images/homepage/features04.webp
  public/assets/images/homepage/features04dark.webp
  public/assets/images/homepage/features05.webp
  public/assets/images/homepage/features05dark.webp
  public/assets/images/homepage/testing.mp4
  public/sitemap-0.xml
  src/components/ThemeImage/index.tsx
  src/pages/_document.tsx
  src/pages/_meta.json
  src/styles/general.scss
  yarn.lock
Labels: type: enhancement

#134 docs: Added the Integrations button
  package.json
  src/pages/_meta.json
  src/pages/docs/_meta.json
  src/pages/docs/assistants.mdx
  src/pages/docs/index.mdx
  src/pages/docs/integrations.mdx
  src/pages/docs/integrations/_meta.json
  src/pages/docs/threads.mdx
  src/pages/docs/use-tools.mdx
  src/pages/integrations/_meta.json
  src/pages/integrations/index.mdx
  src/pages/integrations/interpreter.mdx
  src/pages/integrations/raycast.mdx
  src/pages/integrations/vscode.mdx
  theme.config.tsx
  yarn.lock
Labels: type: documentation

#135 fix: update copy remote api feature
  src/components/Home/Feature/index.tsx
Labels: type: bug

#138 docs: Updated the docs for the v4.12 releases and the new structure
  _redirects
  src/pages/docs/_meta.json
  src/pages/docs/built-in/llama-cpp.mdx
  src/pages/docs/built-in/tensorrt-llm.mdx
  src/pages/docs/desktop-installation/_meta.json
  src/pages/docs/desktop-installation/linux.mdx
  src/pages/docs/desktop-installation/mac.mdx
  src/pages/docs/desktop-installation/windows.mdx
  src/pages/docs/gpu-setup.mdx
  src/pages/docs/gpu-setup/_meta.json
  src/pages/docs/gpu-setup/amd.mdx
  src/pages/docs/gpu-setup/intel.mdx
  src/pages/docs/gpu-setup/mac.mdx
  src/pages/docs/gpu-setup/nvidia.mdx
  src/pages/docs/hardware-setup/_meta.json
  src/pages/docs/index.mdx
  src/pages/docs/installation/desktop.mdx
  src/pages/docs/local-inference/_meta.json
  src/pages/docs/models.mdx
  src/pages/docs/quickstart.mdx
  src/pages/docs/remote-inference/_meta.json
  src/pages/docs/remote-inference/generic-openai.mdx
  src/pages/docs/remote-inference/openrouter.mdx
  src/pages/docs/server-installation/_assets/helm_resources.png
  src/pages/docs/server-installation/_meta.json
  src/pages/docs/server-installation/aws.mdx
  src/pages/docs/server-installation/azure.mdx
  src/pages/docs/server-installation/gcp.mdx
  src/pages/docs/server-installation/onprem.mdx
  src/pages/docs/settings.mdx
  src/pages/docs/tools.mdx
  src/pages/integrations/_meta.json
  src/pages/integrations/coding/vscode.mdx
  src/pages/integrations/function-calling/interpreter.mdx
  src/pages/integrations/index.mdx
  src/pages/integrations/messaging/discord.mdx
  src/pages/integrations/workflow-automation/raycast.mdx
Labels: type: documentation

#141 fix: another og image
  public/assets/images/general/og-throughput-benchmark.png
Labels: type: bug

#142 docs: Updated per new structure
  public/openapi/jan.json
  src/pages/docs/_meta.json
  src/pages/docs/architecture.mdx
  src/pages/docs/built-in/llama-cpp.mdx
  src/pages/docs/desktop-installation.mdx
  src/pages/docs/desktop-installation/linux.mdx
  src/pages/docs/desktop-installation/mac.mdx
  src/pages/docs/desktop-installation/windows.mdx
  src/pages/docs/gpu-setup/_meta.json
  src/pages/docs/gpu-setup/amd.mdx
  src/pages/docs/gpu-setup/intel.mdx
  src/pages/docs/gpu-setup/mac.mdx
  src/pages/docs/gpu-setup/nvidia.mdx
  src/pages/docs/models.mdx
  src/pages/docs/quickstart.mdx
  src/pages/docs/settings.mdx
  src/pages/docs/tools/tools.mdx
Labels: type: documentation

#143 docs: updated the slug and redirects
  _redirects
  src/pages/docs/tools/retrieval.mdx
Labels: type: documentation

#151 docs: Updated the docs contents and inserted images for smooth user journey
  _redirects
  src/pages/docs/_assets/assistant1.gif
  src/pages/docs/_assets/assistant2.gif
  src/pages/docs/_assets/clean.png
  src/pages/docs/_assets/clear.gif
  src/pages/docs/_assets/data-folder.gif
  src/pages/docs/_assets/delete-threads.png
  src/pages/docs/_assets/delete.png
  src/pages/docs/_assets/download.png
  src/pages/docs/_assets/experimental.gif
  src/pages/docs/_assets/gpu.gif
  src/pages/docs/_assets/history.png
  src/pages/docs/_assets/https.gif
  src/pages/docs/_assets/hub.gif
  src/pages/docs/_assets/import-folder.gif
  src/pages/docs/_assets/linux.png
  src/pages/docs/_assets/local-api1.png
  src/pages/docs/_assets/local-api2.png
  src/pages/docs/_assets/local-api3.png
  src/pages/docs/_assets/local-api4.png
  src/pages/docs/_assets/mac2.png
  src/pages/docs/_assets/modelparam.gif
  src/pages/docs/_assets/mymodels.png
  src/pages/docs/_assets/quick-ask.gif
  src/pages/docs/_assets/reset.gif
  src/pages/docs/_assets/retrieval.gif
  src/pages/docs/_assets/settings.png
  src/pages/docs/_assets/specific-model.gif
  src/pages/docs/_assets/ssl.gif
  src/pages/docs/_assets/thread-settings.png
  src/pages/docs/_assets/thread-settings2.png
  src/pages/docs/_assets/windows.png
  src/pages/docs/assistants.mdx
  src/pages/docs/desktop-installation/linux.mdx
  src/pages/docs/desktop-installation/mac.mdx
  src/pages/docs/desktop-installation/windows.mdx
  src/pages/docs/local-api.mdx
  src/pages/docs/models/manage-models.mdx
  src/pages/docs/models/model-parameters.mdx
  src/pages/docs/remote-inference/openai.mdx
  src/pages/docs/settings.mdx
  src/pages/docs/threads.mdx
  src/pages/docs/tools/retrieval.mdx
Labels: type: documentation

#154 integrations: improve Discord bot instructions
  src/pages/integrations/messaging/discord.mdx
Labels: type: enhancement

#155 docs: Updated the docs and inserted images and GIFs
  src/pages/docs/_assets/delete-tensor.gif
  src/pages/docs/_assets/disable-tensor.gif
  src/pages/docs/_assets/download-llama2.gif
  src/pages/docs/_assets/download-phi.gif
  src/pages/docs/_assets/extensions-page.png
  src/pages/docs/_assets/install-tensor.gif
  src/pages/docs/_assets/llama2.gif
  src/pages/docs/_assets/model-groq.gif
  src/pages/docs/_assets/model-openai.gif
  src/pages/docs/_assets/phi.gif
  src/pages/docs/_assets/select-openai.gif
  src/pages/docs/_assets/server-groq.gif
  src/pages/docs/_assets/server-llama2.gif
  src/pages/docs/_assets/server-mistral.gif
  src/pages/docs/_assets/server-openai.gif
  src/pages/docs/_assets/server-phi.gif
  src/pages/docs/_assets/set-tensor.gif
  src/pages/docs/_assets/start-groq.gif
  src/pages/docs/_assets/start-mistral.gif
  src/pages/docs/_assets/start-router.gif
  src/pages/docs/_assets/system-mili.png
  src/pages/docs/_assets/system-monitor.png
  src/pages/docs/_assets/system-slider.png
  src/pages/docs/built-in/llama-cpp.mdx
  src/pages/docs/built-in/tensorrt-llm.mdx
  src/pages/docs/extensions.mdx
  src/pages/docs/local-inference/lmstudio.mdx
  src/pages/docs/local-inference/ollama.mdx
  src/pages/docs/remote-inference/generic-openai.mdx
  src/pages/docs/remote-inference/groq.mdx
  src/pages/docs/remote-inference/mistralai.mdx
  src/pages/docs/remote-inference/openai.mdx
  src/pages/docs/remote-inference/openrouter.mdx
Labels: type: documentation, type: enhancement

#156 docs: manually update stats
  src/components/Home/CTADownload/index.tsx
  src/components/Home/Hero/index.tsx
  src/components/Home/Statistic/index.tsx
Labels: type: documentation

#157 fix: changelog invalid time
  src/pages/changelog.mdx
Labels: type: bug

#158 docs: Updated the documentation
  src/pages/_meta.json
  src/pages/cortex/_meta.json
  src/pages/cortex/built-in/llama-cpp.mdx
  src/pages/cortex/built-in/tensorrt-llm.mdx
  src/pages/cortex/index.mdx
  src/pages/docs/_assets/install-ext.gif
  src/pages/docs/_assets/model-mistral.gif
  src/pages/docs/_meta.json
  src/pages/docs/built-in/llama-cpp.mdx
  src/pages/docs/built-in/tensorrt-llm.mdx
  src/pages/docs/error-codes.mdx
  src/pages/docs/extensions.mdx
  src/pages/docs/installing-extension.mdx
  src/pages/docs/remote-inference/mistralai.mdx
  src/pages/hardware/_meta.json
  src/pages/hardware/ai-computer.mdx
  src/pages/hardware/ai-computer/_meta.json
  src/pages/hardware/ai-computer/gpu.mdx
  src/pages/hardware/index.mdx
  src/pages/integrations/messaging/discord.mdx
  theme.config.tsx
Labels: type: documentation

#137 feat: Update blog for tensorrt-llm based on the revision
  package-lock.json
  package.json
  src/components/Blog/CTA/index.tsx
  src/components/NewsletterForm/index.tsx
  src/components/SocialShareButton/index.tsx
  src/pages/hardware/_meta.json
  src/pages/hardware/ai-computer.mdx
  src/pages/post/_assets/3090s.jpg
  src/pages/post/_assets/4070s.jpg
  src/pages/post/_assets/4090s.png
  src/pages/post/_assets/egpu.jpg
  src/pages/post/_assets/throughput_Comparison.png
  src/pages/post/benchmarking-tensorRT-LLM.mdx
  src/pages/post/bitdefender.mdx
  src/pages/post/data-is-moat.mdx
  src/pages/post/rag-is-not-enough.mdx
  theme.config.tsx
  yarn.lock
Labels: P0: critical, help wanted, type: feature request

#161 fix: Meta
  src/pages/hardware/_meta.json
  src/pages/hardware/ai-computer.mdx
  src/pages/hardware/ai-computer/_meta.json
  src/pages/hardware/ai-computer/gpu.mdx
  src/pages/post/benchmarking-nvidia-tensorrt-llm.mdx
Labels: P0: critical, type: bug, type: documentation

#162 Docs pena team docs
  src/pages/_meta.json
  src/pages/cortex/_meta.json
  src/pages/cortex/built-in/llama-cpp.mdx
  src/pages/cortex/built-in/tensorrt-llm.mdx
  src/pages/cortex/index.mdx
  src/pages/hardware/_meta.json
  src/pages/hardware/index.mdx
  src/pages/integrations/_meta.json
  theme.config.tsx
Labels: type: documentation

#167 docs: Updated the quickstart and managing models per feedbacks
  src/pages/docs/_assets/download-model.gif
  src/pages/docs/_assets/import-hf.gif
  src/pages/docs/installing-extension.mdx
  src/pages/docs/models/manage-models.mdx
  src/pages/docs/quickstart.mdx
Labels: type: documentation, type: enhancement

#169 docs: Updated the redirect links
  _redirects
Labels: type: documentation
